In [8]:
import numpy as np


In [9]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.
def function():
    arr=np.array([1,7,13,105])
    print(arr)
    print(f"Size={arr.size}")


In [10]:
function()

[  1   7  13 105]
Size=4


In [11]:
#2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

arr1=np.array([11,22])
arr2=np.array([21,33])

 

In [12]:
print("comparision-greater")
print(np.greater(arr1,arr2))

print("comparision_greater equal")
print(np.greater_equal(arr1,arr2))

print("comparision-less")
print(np.less(arr1,arr2))

print("comparision-less_equal")
print(np.less_equal(arr1,arr2))

comparision-greater
[False False]
comparision_greater equal
[False False]
comparision-less
[ True  True]
comparision-less_equal
[ True  True]


In [21]:
#3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

print(f"array of 10 zeros")
array=np.zeros(10)
print(array)

print(f"array of 10 ones")
array=np.ones(10)
print(array)

print(f"array of 5 fives")
array=np.ones(5)*5
print(array)

print(f"array of 10 tens")
array=np.ones(10)*10
print(array)

print(f"array of 20 tens")
array=np.ones(20)*10
print(array)

print(f"array of 50 tens")
array=np.ones(50)*10
print(array)



array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 5 fives
[5. 5. 5. 5. 5.]
array of 10 tens
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
array of 20 tens
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10.]
array of 50 tens
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [27]:
#4.Write a NumPy program to create an array of integers from 30 to 70.

print(f"array of intergers fron 30 to 70")
array=np.arange(30,71)
print(array)


array of intergers fron 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [28]:
#5.Write a NumPy program to create an array of integers from 50 to 95.

print(f"array of integers from 50 to 95")
array=np.arange(50,96)
print(array)

array of integers from 50 to 95
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [31]:
#6. Write a NumPy program to create an array of all even integers from 20 to 80.
print(f"array of even numbers")
array=np.arange(20,81,2)
print(array)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [33]:
#7. Write a NumPy program to create an array of all odd integers from 20 to 80.

print(f"array of odd numbers")
array=np.arange(21,80,1)
print(array)


array of odd numbers
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77 78 79]


In [37]:
#8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

print(f"array of random numbers from 10 to 40")
rand_num=np.random.normal(10,40,15)
print(rand_num)

array of random numbers from 10 to 40
[-33.37371869   1.73617971 -27.50156418  56.75299027  62.88711688
  68.13341651  21.27175564  86.62290996  64.15375478  30.59729064
 -56.54873884  69.26323012  44.23460163 -43.9724544   12.29268442]


In [38]:
#9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

print(f"array of ramdom numbers from 30 to 50")
rand_num=np.random.normal(30,50,10)
print(rand_num)

array of ramdom numbers from 30 to 50
[ 42.44741113  27.96638694   5.75133241 108.72040094 120.75781821
  -4.16250091  -4.4327209   34.35458083  13.34649542  25.20249896]


In [48]:
#10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

print(f"array of 20 random numbers from 50 to 90")
rand_num=np.random.normal(50,90,20)
print(rand_num)

array of 20 random numbers from 50 to 90
[ 210.26928824  -37.85698464  -24.4814984   126.37546559  300.22946391
  149.92902722   54.84858229  115.38935502   89.64234156   23.13637819
  121.4921682  -119.49201057  110.95251331  -32.55913571  -36.90832618
   34.56496704   90.72521813   71.79540893  -89.25879173  196.47975117]


In [49]:
#11. Create any two arrays & perform various mathematical operations.
#    i.e. Addition, Substraction, Multiplication, Divide.

array1=np.array([11,22,33,44,55])
array2=np.array([10,20,30,40,50])

In [51]:
print(f"addition:")
a=array1+array2
print(a)

print(f"substraction:")
b=array1-array2
print(b)

print(f"multiplication:")
c=array1*array2
print(c)

print(f"division:")
d=array1/array2
print(d)

addition:
[ 21  42  63  84 105]
substraction:
[1 2 3 4 5]
multiplication:
[ 110  440  990 1760 2750]
division:
[1.1 1.1 1.1 1.1 1.1]


In [47]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

print(f"3*4 matrix:")
matrix=np.arange(10,22).reshape((3,4))
print(matrix)

3*4 matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [54]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

print(f"3*3 matrix")
matrix=np.eye(3)
print(matrix)

3*3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
#14. Write a NumPy program to find the number of rows and columns in a given matrix. 

print(f"matrix:")
matrix=np.arange(10,30).reshape(4,5)
print(matrix)

print(f"rows and columns:")
print(matrix.shape)

matrix:
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
rows and columns:
(4, 5)


In [62]:
#15. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

print(f"5*5 matrix:")
matrix=np.diag([1,2,3,4,5])
print(matrix)

5*5 matrix:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [64]:
#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

print(f"3*3*3 matrix with arbitrary values:")
matrix=np.random.random((3,3,3))
print(matrix)

3*3*3 matrix with arbitrary values:
[[[0.74477692 0.0331236  0.0541975 ]
  [0.67419035 0.09007539 0.74317438]
  [0.50723128 0.772671   0.33878844]]

 [[0.28624798 0.15775299 0.04950275]
  [0.98995033 0.21787539 0.2826805 ]
  [0.06991579 0.31690365 0.2201685 ]]

 [[0.55906979 0.01040017 0.92382028]
  [0.44733573 0.12237096 0.49944866]
  [0.97950683 0.34596094 0.40555492]]]


In [66]:
#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.

print(f"2*3*4 matrix with arbitrary values:")
matrix=np.random.random((2,3,4))
print(matrix)

2*3*4 matrix with arbitrary values:
[[[0.47523099 0.63561572 0.94213508 0.64789773]
  [0.8732991  0.10770068 0.0369963  0.35733156]
  [0.83604147 0.29933481 0.55658548 0.68723936]]

 [[0.65063484 0.76533913 0.66973943 0.28916301]
  [0.8286212  0.06956554 0.67440594 0.16967125]
  [0.37792403 0.53464649 0.88596718 0.45206813]]]


In [67]:
#18. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

list=[11,22,33,44,55]
print(list)
print(f"one-dimensional array:")
array=np.array(list)
print(array)

[11, 22, 33, 44, 55]
one-dimensional array:
[11 22 33 44 55]


In [72]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

print(f"3*3 matrix:")
matrix=np.arange(2,11).reshape((3,3))
print(matrix)


3*3 matrix:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [79]:
#20. Write a NumPy program to create an array with values ranging from 12 to 38.

print(f"array:")
array=np.arange(12,39)
print(array)

array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [82]:
#21. Write a NumPy program to reverse an array (the first element becomes the last).

print(f"array:")
array=np.array([11,22,33,44,55])
print(array)
array=np.flip(array)
print(array)


array:
[11 22 33 44 55]
[55 44 33 22 11]


In [83]:
#22. Write a NumPy program to convert an data type into to a floating type.



In [86]:
#23. Write a NumPy program to convert a list array.

l1=[10,20,30,40,50]
print(l1)
array=np.array([l1])
print(array)

[10, 20, 30, 40, 50]
[[10 20 30 40 50]]


In [88]:
#24. Write a NumPy program to get the element-wise remainder of an array of division.

array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array)
array=np.remainder(array,2)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]
[1 0 1 0 1 0 1 0 1 0]


In [92]:
#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

array=np.arange(20,51)
print(array)

#array=np.ramainder(array,3)
print(np.remainder(array,3))

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
